#+title: Elle Najt's webpage

Welcome to my webpage!

* [[file:blog/index.org][Blog]]

Writing about experiments and ideas.

* [[file:Topics/Math.org][Math]]

I like learning math.

* [[file:Topics/SoftwareDevelopment.org][Software Tools]]

I like improving at my software skills and understanding how systems work. It's empowering to be able to build tools. 

* [[file:Topics/Opinions.org][Opinions]]

Opinions on software development, learning, and building things.

* [[file:Topics/Personal.org][Personal]]

- Meditation, Clowning, Burning Man, other adventures...
- Music I'm making or listening to
- Tools I like

* Professional
I obtained my math PhD Dec 2021 at the University of Wisconsin-Madison, advised by [[http://www.math.wisc.edu/~ellenber/][Jordan Ellenberg]].

[[file:Topics/GradSchoolResearch.org][Here is a catalogue of the research I was involved in during graduate school.]]

Jan 2018 - August 2019 I was a visitor in [[https://people.csail.mit.edu/jsolomon/][Justin Solomon's]] lab at MIT/CSAIL. I worked with him and
[[https://www.math.wsu.edu/faculty/ddeford/][Daryl DeFord]] to [[file:Topics/GradSchoolResearch.org::*Gerrymandering][analyze statistical techniques being used to evaluate gerrymandering.]]

After graduate school I worked as a data scientist at Two Sigma for several years.

Now I am doing AI safety research as an Anthropic fellow, mostly focusing on AI Control and monitoring but with some interpy side projects.

* Internet presence:

[[https://math.stackexchange.com/users/54092/elle-najt/][Stack Exchange]]
[[https://github.com/ElleNajt/][Github]]
