#+title: Elle Najt's webpage

Welcome to my webpage!

Click on the headers to see more about my interests.

* [[file:Topics/Emacs.org][Emacs]]
I love emacs and developing my workflow brings me a lot of happiness. :)

* [[file:Topics/Math.org][Math]]
I like learning math, and writing about what I'm learning clarifies things for me.

* [[file:Topics/SoftwareDevelopment.org][Software Development]]
I've been on an arc of getting better at software engineering skills and other aspects of computer usage.

* [[file:Topics/Personal.org][Personal]]
Meditation, Clowning, Burning Man, other adventures...

* [[file:Topics/Music.org][Music]]
I like music, and also make music on the piano and in ableton.

* [[file:Topics/Consumerism.org][Consumerism]]
Things that benefit me through their consumption: tools, thoughts, medicine.

* Professional
I obtained my math PhD Dec 2021 at the University of Wisconsin-Madison, advised by [[http://www.math.wisc.edu/~ellenber/][Jordan Ellenberg]].

[[file:Topics/GradSchoolResearch.org][Here is a catalogue of the research I was involved in during graduate school.]]

Jan 2018 - August 2019 I was a visitor in [[https://people.csail.mit.edu/jsolomon/][Justin Solomon's]] lab at MIT/CSAIL. I worked with him and
[[https://www.math.wsu.edu/faculty/ddeford/][Daryl DeFord]] to [[file:Topics/GradSchoolResearch.org::*Gerrymandering][analyze statistical techniques being used to evaluate gerrymandering.]]

I currently work as a data scientist on a systematic trading team at Two Sigma. I like it! Obviously all opinions expressed on this webpage are my own.

* Internet presence:

[[https://math.stackexchange.com/users/54092/elle-najt/][Stack Exchange]]
[[https://github.com/ElleNajt/][Github]]
