#+title: Elle Najt's webpage

Welcome to my webpage! It's written in org mode!!

* [[file:Topics/Emacs.org][Emacs]]
I love emacs and working on my workflow experience brings me a lot of happiness. :)

I like sharing the cool features I find, or the things I hack on and add.

* [[file:Topics/Math.org][Math]]
I like learning math, and writing about what I'm learning clarifies things for me.

* [[file:Topics/ComputerScience.org][Computer Science]]
I've been on an arc of getting better at software engineering skills and other aspects of computer touchery.

* [[file:Topics/Personal.org][Personal]]
Meditation, Clowning, Burning Man, other adventures...

* [[file:Topics/Music.org][Music]]
I like music, and also make music on the piano and in ableton.

* [[file:Topics/Consumerism.org][Consumerism]]
Things that benefit me through their consumption; tools, thoughts, medicine.

* Professional
I obtained my math PhD Dec 2021 at the University of Wisconsin-Madison, advised by [[http://www.math.wisc.edu/~ellenber/][Jordan Ellenberg]].

[[file:Topics/GradSchoolResearch.org][Here is a catalogue of the research I was involved in during graduate school.]]

Jan 2018 - August 2019 I was a visitor in [[https://people.csail.mit.edu/jsolomon/][Justin Solomon's]] lab at MIT/CSAIL. I worked with him and
[[https://www.math.wsu.edu/faculty/ddeford/][Daryl DeFord]] to [[file:Topics/GradSchoolResearch.org::*Gerrymandering][analyze statistical techniques being used to evaluate gerrymandering.]]

I currently work as a data scientist on a systematic trading team at Two Sigma. I like it!

* Internet presence:

[[https://math.stackexchange.com/users/54092/elle-najt/][Stack-exchange]]
[[https://github.com/ElleNajt/][Github]]
