#+title: Consumerism

* Tools I love:

Here are some mostly material things that have my life better:

** Good ergonomics:

This matters a lot for flow, and for finding programming [[file:SoftwareDevelopment.org::*Fun][fun]]. Here are my favorite bits of ergonomics:
- A gas monitor arm for getting the right monitor position
- A kinesis 360 keyboard
- A herman-miller embody

These can be aligned so that my whole body feels at ease when I'm working, and it helps me stay in the zone for longer periods of time.

And obviously [[file:Emacs.org][emacs.]]

** Good sleep
- A good bed -- use the money back return offers to iterate!
- A weighted blanket
- A good air filter
- ([[https://slatestarcodex.com/2018/07/10/melatonin-much-more-than-you-wanted-to-know/#post-4987][The right dose of]]) melatonin sometimes
- The right mindset: framing it as trying to rest rather than fall asleep has helped me, as described [[https://tasshin.com/blog/the-gospel-of-naps-according-to-tasshin/][here]].

** Good food
These two things help me stay hydrated and eating well:

- A nutribullet Blender
- A zojirushi hot water dispenser

** Good exercise:
I haven't figured out an exercise I enjoy in a way I can do consistently. Maybe dancing?


* TODO Medical consumption:
I have some medical quality of life issues that I'm trying to solve.

** Allergies
*** <2024-09-23 Mon>
I got retested for allergies today, and they found more reactions using the intradermal tests. Turns out I am allergic to dust mites! Hoping that allergy shots will clear up my lingering night time asthma issues.
