#+title: Tools I Like

* Tools I love:

Here are some mostly material things that have my life better:

** Good ergonomics:

This matters a lot for flow, and for finding programming [[file:Opinions.org::*Fun][fun]]. Here are my favorite bits of ergonomics:
- A gas monitor arm for getting the right monitor position
- A kinesis 360 keyboard
- A herman-miller embody

These can be aligned so that my whole body feels at ease when I'm working, and it helps me stay in the zone for longer periods of time.

And obviously [[file:Emacs.org][emacs.]]

** Good sleep
- A good bed -- use the money back return offers to iterate!
- A weighted blanket
- A good air filter
- ([[https://slatestarcodex.com/2018/07/10/melatonin-much-more-than-you-wanted-to-know/#post-4987][The right dose of]]) melatonin sometimes
- The right mindset: framing it as trying to rest rather than fall asleep has helped me, as described [[https://tasshin.com/blog/the-gospel-of-naps-according-to-tasshin/][here]].
- Going to bed regularly on time. 
- Reading fiction in bed is really helpful for winding down in an enjoyable way.

** Good food
These two things help me stay hydrated and eating well:

- A nutribullet Blender
- A zojirushi hot water dispenser

** Good exercise:

I'm liking finding opportunities to move and to push my body. Some ways that are always available:

- Dancing
- Running up stairs

** Allergy shots

Having allergies sucks. Get allergy shots if you can. Some doctors offer rush shots that can move you through the early slog faster.

