#+title: Emacs
#+PROPERTY: :exports both

* Config:

[[https://github.com/ElleNajt/emacs][Here's my emacs config!]]

* I'm an org babel for data science evangelist!

[[https://github.com/ElleNajt/ElleNajt.github.io/blob/master/Code/OrgBabelExample/example.org][Here's an example of an org babel file as a generic data science notebook!]]
[[file:../Code/OrgBabelExample/example.org][Here's what it looks like when published to html.]]

Seriously this is great -- it's changed my life.

** TODO Write a post about this.
SCHEDULED: <2024-09-25 Wed>

* Emacs is really fun, that's the main reason I like it!

Fun is a signal, not frivolity.
Fun is leads to flow, and flow leads to deep work and curiosity and creativity.
All of this leads to more productivity.

* Favorite features:
** Dired:
- wdired is magic
- ! then command (e.g. firefox) on the highlighted file = yay
- tab on a file
- M for changing permissions
- Mapping W to dired-do-eww

** Org todos / agenda

I love that I can collect todos from my org babel notebooks! No more running todo lists, org just collects them in their natural contexts.

** Org publish:
*** Cool features:
- I can drop todos in my webpage and have them hidden by default by visible in my agenda.
*** Challenges I ran into :

- Needed to set (org-store-link) to be relative by default; otherwise depending on folder structure emacs can insert them as absolute paths, which results in links in the published page that point to files that don't exist.

   #+begin_src elisp
   (setq org-link-file-path-type 'relative)
   #+end_src


- I don't know how to get publish to handle links to files in folders that have spaces
***** TODO Fix the spaces in folders stuff.
***** TODO Also make auto-index work, it's not respecting folder structure.


