#+title: Emacs
#+PROPERTY: :exports both

* Config:

[[https://github.com/ElleNajt/emacs][Here's my emacs config!]]

* I'm an org babel for data science evangelist!

[[https://github.com/ElleNajt/ElleNajt.github.io/blob/master/Code/OrgBabelExample/example.org][Here's an example of an org babel file as a generic data science notebook!]]
[[file:../Code/OrgBabelExample/example.org][Here's what it looks like when published to html.]]

Seriously this is great -- it's changed my life.

** TODO Write a post about this.
SCHEDULED: <2024-09-25 Wed>

* Why emacs:
** Emacs is really fun!

That's the main reason I like it!
Fun is a signal, not frivolity.
Fun is leads to flow, and flow leads to deep work and curiosity and creativity.
All of this leads to more productivity.

** Better than a UI or a CLI:

I also find that the transient menu style interface works fits much better in my brain than CLI or standard UIs.

This applies to:
- Magit
- Dired
- M-x anything



* Favorite features:

** yassnippets

They're a great way to optimize writing code. It's a nice feeling to design yas snippets so they work smoothly together.

See this inspiring [[https://karthinks.com/software/latex-input-for-impatient-scholars/][fast latex input via snippets]].

** Magit

I don't think I would have learned git so throughoughly without magit.

** Dired

- wdired is magic -- I love being able to treat things that don't feel editable as editable, actually. (Consult-ripgep embark has the same flavor.)
- ! or & then command (e.g. firefox) on the highlighted file(s) = yay
  it's also smart about guessing what you want to do!
- Tab on a file
- M for changing permissions
- Mapping W to dired-do-eww

** Org todos / agenda

I love that I can collect todos from my org babel notebooks! No more running todo lists, org just collects them in their natural contexts.

** Org publish:
*** Cool features:
- I can drop todos in my webpage and have them hidden by default by visible in my agenda.
*** Challenges I ran into :

- Needed to set (org-store-link) to be relative by default; otherwise depending on folder structure emacs can insert them as absolute paths, which results in links in the published page that point to files that don't exist.

   #+begin_src elisp
   (setq org-link-file-path-type 'relative)
   #+end_src


- I don't know how to get publish to handle links to files in folders that have spaces
***** TODO Fix the spaces in folders stuff.
***** TODO Also make auto-index work, it's not respecting folder structure.


