#+title: Emacs
#+PROPERTY: :exports both
#+OPTIONS: html-link-use-abs-url:nil
#+OPTIONS: html-link-home:""
#+OPTIONS: html-link-org-files-as-html:t

* I'm an org babel for data science evangelist!
Seriously this is great -- it's changed my life. Will write more on that later.

[[https://github.com/ElleNajt/ElleNajt.github.io/blob/master/Code/OrgBabelExample/example.org][Here's an example of an org babel file as a generic data science notebook!]]

* Emacs is really fun, that's the main reason I like it.
* [[https://github.com/ElleNajt/emacs][Here's my emacs config!]]
* Dired features I'm enjoying

** wdired is magic
** ! then command (e.g. firefox) on the highlighted file = yay
** tab on a file
** M for changing permissions
** Mapping W to dired-do-eww


* Other org stuff
** <2024-09-23 Mon> Some struggles getting org publish to work, but I have a webpage
- Publish seems confused by folders that have spaces?
- auto inserted links ( via SPC n l -> C-c C-l workflow) were not always relative, which lead to links breaking. I think this was fixed with:

   #+begin_src elisp

(setq org-link-file-path-type 'relative)
   #+end_src

- Calling publish from doom is slow on my machine (probably downstream of it being somewhat slow to load an org file for the first time in my config on my virtual machine) so I run:

  #+begin_src bash

  emacs --batch -l ./publish.el
  #+end_src


- Now that it's working it's awesome though. :)
