#+SETUPFILE: ~/.doom.d/org-templates/standard.org
#+title: Grad School Research

* Gerrymandering

[[https://www.supremecourt.gov/DocketPDF/21/21-1086/230272/20220718153650363_21-1086%2021-1087%20bsac%20Computational%20Redistricting%20Experts.pdf][Some of the work I did was cited in an amicus brief at the supreme court!]]

This work was featured [[https://grad.wisc.edu/2020/04/23/mathematics-research-builds-better-ways-to-identify-gerrymandering/][This work was featured here.]].

** [[https://arxiv.org/abs/1908.08881][Complexity and Geometry of Sampling Connected Graph Partitions]]
In this paper, we prove intractability results about sampling from the set of partitions of a planar graph into connected components. Our proofs are motivated by a technique introduced by Jerrum, Valiant, and Vazirani. Moreover, we use gadgets inspired by their technique to provide families of graphs where the "flip walk" Markov chain used in practice for this sampling task exhibits exponentially slow mixing. Supporting our theoretical results we present some empirical evidence demonstrating the slow mixing of the flip walk on grid graphs and on real data. Inspired by connections to the statistical physics of self-avoiding walks, we investigate the sensitivity of certain popular sampling algorithms to the graph topology. Finally, we discuss a few cases where the sampling problem is tractable. Applications to political redistricting have recently brought increased attention to this problem, and we articulate open questions about this application that are highlighted by our results.

** [[https://arxiv.org/abs/1905.03173][The Gerrymandering Jumble: Map Projections Permute Districts' Compactness Scores]]
In political redistricting, the compactness of a district is used as a quantitative proxy for its fairness. Several well-established, yet competing, notions of geographic compactness are commonly used to evaluate the shapes of regions, including the Polsby-Popper score, the convex hull score, and the Reock score, and these scores are used to compare two or more districts or plans. In this paper, we prove mathematically that any map projection from the sphere to the plane reverses the ordering of the scores of some pair of regions for all three of these scores. Empirically, we demonstrate that the effect of using the Cartesian latitude-longitude projection on the order of Reock scores is quite dramatic.

** (Ongoing?) Further research into metamandering on real data.

[[file:abstraction_correction.org::Correction to an abstract for a presentation:][I spoke about some of the in-progress work at the AMS Special Session on Partitioning and Redistricting, and have a correction to my abstract.]]

* Sampling problems
** [[file:../Code/Latex/PolytopePaper/The_intractability_of_uniformly_sampling_and_counting_the_vertices_of_a_polytope_under_branchwidth_constraints__Arxiv_Version_.pdf::%PDF-1.5][Uniform sampling of vertices of polytopes with bounded branchwidth is still hard]]

Abstract: We consider the complexity of sampling vertices of a polytope. A theorem of Khachiyan uses the circulation polytope of a directed graph to show that this sampling problem is NP-hard, in the sense that a polynomial time sampler would imply NP = RP. It is known, also by work of Khachiyan et al., that the vertex enumeration problem is NP-hard for polyhedra, while it remains open for polytopes. However, bounding the branchwidth has been shown to provide a total polynomial time algorithm for the polytope vertex enumeration problem, and it is therefore natural to ask whether bounding branchwidth makes vertex sampling tractable. We investigate this question and demonstrate the NP-hardness of uniformly sampling vertices of a polytope given by $\{ Ax = b x \geq 0 \}$, where $A$ has branchwidth <= 4. To do so, we develop gadgets that build bounded branchwidth polytopes that have many vertices over certificates of an NP-hard problem. In an appendix, we apply this gadget to provide an alternative proof a recent theorem of Guo and Jerrum about sampling vertices from another class of polytopes. We also study some related questions, such as the branchwidth of the circulation polytope, and show that the vertices of a circulation polytope of bounded branchwidth can be sampled efficiently.

** Sampling connected partitions for Bayesian statistics

* The Legend of Zelda
I had the great pleasure letting my inner child contribute a theorem to this paper:

** [[https://thaijmath2.in.cmu.ac.th/index.php/thaijmath/article/view/1539][The Legend of Zelda: The Complexity of Mechanics]]
Abstract: We analyze some of the many game mechanics available to Link in the classic Legend of Zelda series of video games. In each case, we prove that the generalized game with that mechanic is polynomial, NP-complete, NP-hard and in PSPACE, or PSPACE-complete. In the process we give an overview of many of the hardness proof techniques developed for video games over the past decade: the motion-planning-through-gadgets framework, the planar doors framework, the doors-and-buttons framework, the “Nintendo” platform game / SAT framework, and the collectible tokens and toll roads / Hamiltonicity framework.

Erik Demaine's course on complexity lower bounds via video games was pedagogically brilliant: [[https://courses.csail.mit.edu/6.892/spring19/][Fun with Hardness Proofs]]
Research and math education should be fun and playful! Scientific creativity is a form of play.

* On asking for help:

In graduate school I wrote:

> I believe that doing science is a network activity. If the knowledge I need to advance my research goals is likely to be basic knowledge to some experts who I can be connected to through stack exchange, then it is my responsibility as a researcher to put aside my ego and ask for help. It is unreasonable to expect to be able to replicate the same happy accidents that brought scientific communities to new insights.

I think, in retrospect, I could have asked for a lot more help. :)
