#+title: Math

Here are the math topics I'm interested in:

* Statistics $\mathbb{P}(A)$

It's pretty cool that we can understand things about the world from limited data; probability is a microscope!

* Assorted Pure Math  $\mathcal{F}(X)$

Here are some of my favorite theorems:
- 27 Lines on a smooth cubic, in particular the argument via the 27 fold covering of the parameter space of smooth cubics with the configuration space of (Cubic, Line).
- [[https://en.wikipedia.org/wiki/Steinitz%27s_theorem][Steinitz's theorem]] : The graphs of 3 polytopes are the 3-vertex connected planar graphs!
- Rapid mixing of the basis-exchange-walk on spanning trees of a graph: Take a graph $G$, and let $\mathcal{T}$ be the set of spanning trees of the graph. There is a random walk on $\mathcal{T}$ wherein standing at a tree $T$ you take an edge in $G \setminus E(T)$ -- in $G$ but not an edge of $T$ - and add it to T, forming a cycle in $T$,  and then you delete a random edge in that cycle. This mixes rapidly, so after a polynomial in $|G|$ number of steps you're at approximately a uniformly random spanning tree.

* Research

In graduate school I did research on Markov chains that were being used to analyze political redistricting, along with some related problems. [[file:GradSchoolResearch.org][You can find an overview of my research here.]]

* Competition Math $x + y \geq 2\sqrt{xy}$

I wasn't successful at competition math in high school, so I'm enjoying learning how to become good at it as a means of doing some emotional processing and improving my general problem solving skills. I'm doing this by working with a tutor who is better than me at solving mathematical problems and we are working through Engel's "Problem-Solving strategies."

** Some problem solving lessons I'm learning:
*** <2024-10-05 Sat>
Noticed that I got fixated on solving one of the example problems. I did eventually solve it, which I felt really good about, though I found a different solution from the one in the book, meaning that from my struggles I didn't learn how the problem was an example of the problem solving technique of invariants.

I reflect on how I had internalized the idea that it is virtuous to struggle to solve a problem, which I am questioning - certainly there is virtue in solving hard problems, and value in developing the skill of being okay with frustration. But I think the "struggle with problems" mindset is one that makes the most sense when at the core ideas have been learned, and my goal here is to become a better mathematical problem solver. I discussed this with my tutor, and he cited some research showing that studying diversity of topics and simply doing a lot of problems is more effective, and we both agreed that it made sense to [[file:SoftwareDevelopment.org::*Fun][optimize for fun]].

As we were working on another problem I started thinking about how it was hard to let go of an approach to a problem, even when I've become convinced that it won't work, because of the appeal of an idea working out.

There is a useful [[file:Personal.org::*Meditation][forgiveness practice]] here also: forgiveness for not being able to come up with an idea, and forgiveness for an approach not working. I wonder if practice that in this context will make my attitudes more fluid.

*** <2024-09-26 Thu>

I can get stuck in an overly formal way of thinking about problems; e.g. pattern matching what I see against facts I know. It can be useful to notice mindfully when I'm in that mindset and step back into a more heuristic and embodied mindframe.

*** <2024-09-19 Thu>

Mistakes can lead to solutions; it's important to not avoid thinking about how to correct an error out of avoidant shame around doing something "dumb." This effect can be very subtle! Forgive yourself for not understanding. ^^

#+begin_src qoute
To fear the error and to fear the truth are one and the same. One who fears to
be wrong is powerless to discover. It is when we are afraid of making mistakes
that the mistake inside us becomes immovable like a rock.  Because in our fear,
we cling to what we have decreed to be “true”, or what has always been presented
to us as “true”. If we are moved, not by the fear of seeing an illusory security
vanish, but by a thirst for knowing, then error, like suffering or sorrow, will
cross us without ever becoming frozen, and the trace of its passage will be a
renewed understanding.
- Alexander Grothendieck
#+end_src
