#+SETUPFILE: ~/.doom.d/org-templates/standard.org
#+title: Math

Here are the math topics I'm interested in:

* Statistics $\mathbb{P}(A)$

It's pretty cool that we can understand things about the world from limited data; probability is a microscope!

* Assorted Pure Math  $\mathcal{F}(X)$

Some favorite theorems:
- 27 Lines on a smooth cubic, in particular the argument via the 27 fold covering of the parameter space of smooth cubics with the configuration space of (Cubic, Line).
- [[https://en.wikipedia.org/wiki/Steinitz%27s_theorem][Steinitz's theorem]] : The graphs of 3 polytopes are the 3-vertex connected planar graphs!


* Theoretical Computer Science $T(x)$

A lot of my favorite theorems are arguably theoretical computer science, here are some cool ones:

- Rapid mixing of the basis-exchange-walk on spanning trees of a graph: Take a graph $G$, and let $\mathcal{T}$ be the set of spanning trees of the graph. There is a random walk on $\mathcal{T}$ wherein standing at a tree $T$ you take an edge in $G \setminus E(T)$ -- in $G$ but not an edge of $T$ - and add it to T, forming a cycle in $T$,  and then you delete a random edge in that cycle. This mixes rapidly, so after a polynomial in $|G|$ number of steps you're at approximately a uniformly random spanning tree.
-

* Competition Math $x + y \geq 2\sqrt{xy}$

I wasn't very good at competition math in high school, so I'm enjoying learning how to become good at it as a means of doing some emotional processing and improving my general problem solving skills.
