#+title: Software Tools

I like building and learning tools. Time spent reducing frictions pays dividends.

* Side projects:

I love org babel notebooks, they're much more ergonomic than jupyter notebooks. Out of the box they are missing features, but I've been adding the missing features over time:
- [[https://github.com/ElleNajt/ob-python-extras][ob-python-extras]] - Making org babel a full-featured replacement for jupyter notebooks
- [[https://github.com/ElleNajt/vibe-duet/][vibe-duet]] - Tools for vibe coding music with strudel. Try it out! It's fun. :)
- [[https://github.com/ElleNajt/meta-agent-shell][meta-agent-shell]] - Multi agent management in emacs agent-shell
- [[https://github.com/ElleNajt/agent-bedtime][agent-bedtime]] - So coding agents can send you to bed
- [[https://github.com/ElleNajt/agent-timecard][agent-timecard]] - Get reports on how you're spending time, based on conversation turns with coding agents
- [[https://github.com/ElleNajt/acp-mobile][acp-mobile]] - So you can take coding agents with you everywhere (wip)
- [[https://github.com/ElleNajt/oneko-macs][oneko-macs]] - A silly hack to have a neko cat in emacs

* Tools I love:

** Emacs

I love being able to shape my editor into a glove that fits me and my idiosyncrasies. This *so* easy now that we have coding agents. 

#+begin_quote
What is emacs? Emacs is Freedom! Freedom to control how your software behave! Emacs is interconnectedness! All your tools can interact with each other as first class citizens! Emacs is eternal! We've been using emacs since the 70s, and when we're all gerbil-humans living under AI rule in 2035, well still be using emacs! - Me
#+end_quote

** Org-mode

I love working in org babel notebooks, they're much more ergonomic than jupyter notebooks. Out of the box they are missing features, but I've been adding the missing features here over time [[https://github.com/ElleNajt/ob-python-extras][ob-python-extras]] . 

This webpage generated from org mode files.

** Nix

I think Nix/NixOS is a good choice in an increasingly LLM agent driven world; they can read your config and edit, and you can see what they changed and roll back if things go wrong. It also makes it easy to spin up VMs out of your environment. 

** Git

I love git and versioning all sorts of things! I used to not like it very much, but it turned out I was just missing a clear mental model of what it was doing --  [[https://git-scm.com/book/en/v2][pro-git]] helped a lot!

** LLMs

I live inside of Claude Code (inside of emacs). 

** Tests

I like tests as ways to guarantee behavior. They cost nothing to build because of LLMs. 

